const DATA_URL='https://sziaumkwyxodhtuaxlhg.supabase.co/functions/v1/dashboard-data';
const MANAGE_URL='https://sziaumkwyxodhtuaxlhg.supabase.co/functions/v1/manage-products';
let state={products:[],history:[],generated_at:null};
let currentTab='overview',changeFilter='all',detailGroupKey=null,toastTimer,adminWaiter=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=v=>v==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v));
const dt=v=>v?new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const parseMoney=v=>{if(!v)return null;const n=Number(String(v).replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''));return Number.isFinite(n)&&n>0?n:null};
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function adminToken(){return sessionStorage.getItem('radarAdmin')||''}
function requireAdmin(){if(adminToken())return Promise.resolve(adminToken());$('#adminDialog').showModal();return new Promise((resolve,reject)=>adminWaiter={resolve,reject})}
async function manage(payload){const token=await requireAdmin();const r=await fetch(MANAGE_URL,{method:'POST',headers:{'content-type':'application/json','x-admin-token':token},body:JSON.stringify(payload)});const j=await r.json().catch(()=>({error:'Resposta inválida'}));if(r.status===401){sessionStorage.removeItem('radarAdmin');toast('Senha administrativa inválida');throw Error(j.error||'Não autorizado')}if(!r.ok)throw Error(j.error||'Falha na operação');return j}
function groups(){const map=new Map();for(const p of state.products){const key=p.group_key||p.model||p.id;if(!map.has(key))map.set(key,{key,name:p.group_name||p.name,model:p.model||'',gpu:p.gpu||'',rank:Number(p.recommendation_rank??100),offers:[]});map.get(key).offers.push(p)}return [...map.values()]}
function hist(id){return state.history.filter(h=>h.product_id===id).map(h=>({price:Number(h.price),checked_at:h.checked_at})).sort((a,b)=>new Date(a.checked_at)-new Date(b.checked_at))}
function latestRealChange(offer){const h=hist(offer.id),distinct=[];for(const x of h){if(!Number.isFinite(x.price))continue;if(!distinct.length||Math.abs(distinct.at(-1).price-x.price)>.009)distinct.push(x)}if(distinct.length<2)return null;const before=distinct.at(-2),after=distinct.at(-1),delta=after.price-before.price;if(Math.abs(delta)<.01)return null;return{offer,before:before.price,after:after.price,delta,pct:delta/before.price*100,checked_at:after.checked_at}}
function groupChanges(g){return g.offers.map(latestRealChange).filter(Boolean).sort((a,b)=>{const ac=a.pct<0?0:1,bc=b.pct<0?0:1;if(ac!==bc)return ac-bc;return ac===0?a.pct-b.pct:b.pct-a.pct})}
function groupPrice(g){const active=g.offers.filter(o=>o.active);const live=active.filter(o=>o.current_price!=null&&!o.last_error).sort((a,b)=>Number(a.current_price)-Number(b.current_price));const known=active.filter(o=>o.current_price!=null).sort((a,b)=>Number(a.current_price)-Number(b.current_price));return{offer:live[0]||known[0]||null,live:!!live[0]}}
function targetOf(g){const p=g.offers.find(o=>o.target_price!=null);return p?Number(p.target_price):null}
function latestCheck(g){return g.offers.map(o=>o.last_checked_at).filter(Boolean).sort().at(-1)||null}
function groupStats(g){const gp=groupPrice(g),target=targetOf(g),changes=groupChanges(g),drop=changes.find(c=>c.pct<0)||null;return{...gp,target,changes,drop,last:latestCheck(g),reached:gp.offer&&target!=null&&Number(gp.offer.current_price)<=target}}
function allChanges(){const out=[];for(const g of groups())for(const c of groupChanges(g))out.push({...c,group:g});return out.sort((a,b)=>{const ac=a.pct<0?0:1,bc=b.pct<0?0:1;if(ac!==bc)return ac-bc;return ac===0?a.pct-b.pct:b.pct-a.pct})}
function iconArrow(){return '<svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg>'}
function switchTab(tab){currentTab=tab;$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.view').forEach(v=>v.classList.add('hidden'));$('#'+tab+'View').classList.remove('hidden');if(tab==='changes')renderChanges();if(tab==='models')renderModels()}
function renderOverview(){const gs=groups(),changes=allChanges(),drops=changes.filter(c=>c.pct<0),targets=gs.filter(g=>targetOf(g)!=null);const reached=targets.filter(g=>groupStats(g).reached);const activeOffers=state.products.filter(p=>p.active);const liveOffers=activeOffers.filter(p=>p.current_price!=null&&!p.last_error);const best=drops[0];$('#bestDropMetric').textContent=best?`-${Math.abs(best.pct).toFixed(1).replace('.',',')}%`:'—';$('#bestDropName').textContent=best?best.group.name:'Nenhuma queda registrada';$('#targetMetric').textContent=`${reached.length} de ${targets.length}`;$('#monitorMetric').textContent=`${liveOffers.length} ao vivo`;$('#monitorSub').textContent=`${activeOffers.length} ofertas ativas · ${gs.length} modelos`;const top=$('#topOpportunities');top.innerHTML='';drops.slice(0,5).forEach((c,i)=>{const row=document.createElement('div');row.className='opportunity-row';row.innerHTML=`<div class="opportunity-name"><span class="rank">${i+1}</span><div><strong>${esc(c.group.name)}</strong><small>${esc(c.offer.store||new URL(c.offer.url).hostname)} · ${dt(c.checked_at)}</small></div></div><div class="price-shift"><del>${money(c.before)}</del><strong>${money(c.after)}</strong></div><div class="opportunity-saving"><span class="drop-pill">▼ ${Math.abs(c.pct).toFixed(2).replace('.',',')}%</span><strong>economia ${money(Math.abs(c.delta))}</strong><small>desde a leitura anterior</small></div><button class="row-action" data-open-group="${esc(c.group.key)}" aria-label="Abrir detalhes">${iconArrow()}</button>`;top.appendChild(row)});$('#noOpportunities').classList.toggle('hidden',drops.length>0);const tl=$('#targetList');tl.innerHTML='';targets.sort((a,b)=>{const sa=groupStats(a),sb=groupStats(b);if(sa.reached!==sb.reached)return sa.reached?-1:1;const ga=sa.offer?Number(sa.offer.current_price)-sa.target:1e12,gb=sb.offer?Number(sb.offer.current_price)-sb.target:1e12;return ga-gb}).forEach(g=>{const s=groupStats(g),cur=s.offer?Number(s.offer.current_price):null,gap=cur!=null?cur-s.target:null,pct=cur!=null?Math.max(0,Math.min(100,s.target/cur*100)):0;const r=document.createElement('div');r.className='target-row';r.innerHTML=`<div class="target-name"><strong>${esc(g.name)}</strong><small>${s.offer?esc(s.offer.store||'loja'):'sem preço'} · ${s.live?'preço ao vivo':'último conhecido'}</small></div><div class="target-price"><strong>${money(cur)}</strong><small>meta ${money(s.target)}</small></div><div class="progress-wrap"><div class="progress-top"><span>${s.reached?'Meta atingida':gap!=null?`faltam ${money(Math.max(0,gap))}`:'sem leitura'}</span><span>${Math.round(pct)}%</span></div><div class="progress-track"><div class="progress-bar ${s.reached?'reached':''}" style="width:${pct}%"></div></div></div><button class="row-action" data-open-group="${esc(g.key)}">${iconArrow()}</button>`;tl.appendChild(r)});$('#noTargets').classList.toggle('hidden',targets.length>0)}
function renderChanges(){let items=allChanges();if(changeFilter==='drops')items=items.filter(x=>x.pct<0);if(changeFilter==='rises')items=items.filter(x=>x.pct>0);const list=$('#changesList');list.innerHTML='';items.forEach(c=>{const down=c.pct<0,d=document.createElement('article');d.className=`change-item ${down?'drop':'rise'}`;d.innerHTML=`<div class="change-main"><strong>${esc(c.group.name)}</strong><small>${esc(c.offer.store||new URL(c.offer.url).hostname)} · mudou em ${dt(c.checked_at)}</small></div><div class="change-prices"><del>${money(c.before)}</del><strong>${money(c.after)}</strong></div><div class="change-delta"><strong>${down?'▼':'▲'} ${Math.abs(c.pct).toFixed(2).replace('.',',')}%</strong><small>${down?'economia':'aumento'} de ${money(Math.abs(c.delta))}</small></div><button class="row-action" data-open-group="${esc(c.group.key)}">${iconArrow()}</button>`;list.appendChild(d)});$('#noChanges').classList.toggle('hidden',items.length>0)}
function renderModels(){const query=$('#searchInput').value.trim().toLowerCase(),gpu=$('#gpuFilter').value,sort=$('#sortModels').value;let gs=groups().filter(g=>(!query||`${g.name} ${g.model} ${g.gpu}`.toLowerCase().includes(query))&&(gpu==='all'||g.gpu===gpu));gs.sort((a,b)=>{const sa=groupStats(a),sb=groupStats(b);if(sort==='price')return (sa.offer?Number(sa.offer.current_price):1e12)-(sb.offer?Number(sb.offer.current_price):1e12);if(sort==='drop')return (sa.drop?.pct??999)-(sb.drop?.pct??999);if(sort==='name')return a.name.localeCompare(b.name);return a.rank-b.rank||a.name.localeCompare(b.name)});const list=$('#modelList');list.innerHTML='';gs.forEach(g=>{const s=groupStats(g),price=s.offer?Number(s.offer.current_price):null,el=document.createElement('article');el.className='model-card';el.tabIndex=0;el.dataset.openGroup=g.key;el.innerHTML=`<div class="model-left"><div class="model-title">${esc(g.name)}</div><div class="chip-row">${g.model?`<span class="chip">${esc(g.model)}</span>`:''}${g.gpu?`<span class="chip gpu">${esc(g.gpu)}</span>`:''}${(g.rank===1||(g.rank>=20&&g.rank<=22))?`<span class="chip recommended">${g.rank===1?'Minha escolha':'Alternativa'}</span>`:''}</div><div class="model-meta"><span>${g.offers.length} loja${g.offers.length===1?'':'s'}</span><span>${s.live?'preço ao vivo':'último conhecido'}</span>${s.drop?`<span>queda ${Math.abs(s.drop.pct).toFixed(1).replace('.',',')}%</span>`:''}</div></div><div class="model-price"><span>melhor preço</span><strong>${money(price)}</strong><small>${s.reached?'<span class="drop-pill">meta atingida</span>':s.target!=null?`meta ${money(s.target)}`:'sem meta'}</small></div><button class="model-open" data-open-group="${esc(g.key)}">${iconArrow()}</button>`;list.appendChild(el)});$('#noModels').classList.toggle('hidden',gs.length>0)}
function renderDetail(key){const g=groups().find(x=>x.key===key);if(!g)return;detailGroupKey=key;const s=groupStats(g);$('#detailName').textContent=g.name;$('#detailChips').innerHTML=`${g.model?`<span class="chip">${esc(g.model)}</span>`:''}${g.gpu?`<span class="chip gpu">${esc(g.gpu)}</span>`:''}${(g.rank===1||(g.rank>=20&&g.rank<=22))?`<span class="chip recommended">${g.rank===1?'Minha escolha':'Alternativa'}</span>`:''}`;$('#detailSummary').innerHTML=`<div class="detail-stat"><span>Melhor preço</span><strong>${money(s.offer?.current_price)}</strong></div><div class="detail-stat"><span>Sua meta</span><strong>${money(s.target)}</strong></div><div class="detail-stat"><span>Status</span><strong>${s.reached?'✓ Na meta':s.live?'Monitorando':'Último conhecido'}</strong></div>`;$('#detailStoresCount').textContent=`${g.offers.length} oferta${g.offers.length===1?'':'s'}`;$('#detailOffers').innerHTML=g.offers.slice().sort((a,b)=>(a.last_error?1:0)-(b.last_error?1:0)||(Number(a.current_price)||1e12)-(Number(b.current_price)||1e12)).map(o=>`<div class="offer-row"><div class="offer-store"><strong>${esc(o.store||new URL(o.url).hostname)}</strong><small>${o.active?'ativo':'pausado'} · ${o.last_error?'último preço conhecido':'preço ao vivo'}</small></div><div class="offer-price">${money(o.current_price)}</div><div class="offer-time">${dt(o.last_checked_at)}</div><div class="offer-actions"><a class="mini-button" href="${esc(o.url)}" target="_blank" rel="noopener">Abrir</a><button class="mini-button" data-check-id="${o.id}" type="button">Verificar</button><button class="mini-button danger" data-delete-offer="${o.id}" type="button">Remover</button></div></div>`).join('');const cs=groupChanges(g);$('#detailHistory').innerHTML=cs.length?cs.map(c=>`<div class="history-row"><strong>${esc(c.offer.store||'Loja')} · ${money(c.before)} → ${money(c.after)}</strong><span>${dt(c.checked_at)}</span><span class="${c.pct<0?'drop-pill':'rise-pill'}">${c.pct<0?'▼':'▲'} ${Math.abs(c.pct).toFixed(2).replace('.',',')}%</span></div>`).join(''):'<div class="empty-inline">Nenhuma mudança real registrada para este modelo.</div>';$('#detailTargetBtn').textContent=s.target!=null?'Alterar meta':'Definir meta';$('#detailToggleBtn').textContent=g.offers.some(o=>o.active)?'Pausar grupo':'Retomar grupo';$('#detailDialog').showModal()}
function renderAll(){const changes=allChanges();$('#changeBadge').textContent=changes.length;const checks=state.products.map(p=>p.last_checked_at).filter(Boolean).sort();$('#lastSync').textContent=checks.length?dt(checks.at(-1)):dt(state.generated_at);renderOverview();if(currentTab==='changes')renderChanges();if(currentTab==='models')renderModels();$('#loadingState').classList.add('hidden');$('.view:not(.hidden)')||switchTab(currentTab)}
async function load(){try{$('#errorBox').classList.add('hidden');const r=await fetch(DATA_URL+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();state={products:d.products||[],history:d.history||[],generated_at:d.generated_at};renderAll();switchTab(currentTab)}catch(e){$('#loadingState').classList.add('hidden');$('#errorBox').textContent='Não foi possível carregar os dados agora. '+e.message;$('#errorBox').classList.remove('hidden')}}
$$('.tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$$('[data-go-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.goTab)));$$('.segment').forEach(b=>b.addEventListener('click',()=>{changeFilter=b.dataset.changeFilter;$$('.segment').forEach(x=>x.classList.toggle('active',x===b));renderChanges()}));
$('#searchInput').addEventListener('input',renderModels);$('#gpuFilter').addEventListener('change',renderModels);$('#sortModels').addEventListener('change',renderModels);$('#refreshBtn').addEventListener('click',()=>{toast('Atualizando dados…');load()});$('#adminBtn').addEventListener('click',()=>$('#adminDialog').showModal());$('#addBtn').addEventListener('click',async()=>{try{await requireAdmin();$('#addDialog').showModal()}catch(_){}});
document.addEventListener('click',e=>{const open=e.target.closest('[data-open-group]');if(open){renderDetail(open.dataset.openGroup);return}const close=e.target.closest('[data-close]');if(close){document.getElementById(close.dataset.close).close()}});document.addEventListener('keydown',e=>{const card=e.target.closest?.('.model-card[data-open-group]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();renderDetail(card.dataset.openGroup)}});
$('#adminForm').addEventListener('submit',e=>{e.preventDefault();const t=$('#adminToken').value.trim();if(!t)return;sessionStorage.setItem('radarAdmin',t);$('#adminDialog').close();$('#adminToken').value='';toast('Admin desbloqueado nesta aba');adminWaiter?.resolve(t);adminWaiter=null});$('#adminDialog').addEventListener('close',()=>{if(adminWaiter){adminWaiter.reject(Error('Cancelado'));adminWaiter=null}});
$('#addForm').addEventListener('submit',async e=>{e.preventDefault();const btn=$('#addSubmit');btn.disabled=true;btn.textContent='Adicionando…';try{await manage({action:'add',url:$('#addUrl').value.trim(),model:$('#addModel').value.trim()||null,target_price:parseMoney($('#addTarget').value)});e.target.reset();$('#addDialog').close();toast('Oferta adicionada');await load()}catch(err){toast(err.message)}finally{btn.disabled=false;btn.textContent='Adicionar ao radar'}});
$('#targetForm').addEventListener('submit',async e=>{e.preventDefault();try{await manage({action:'update_group_target',group_key:$('#targetGroupKey').value,target_price:parseMoney($('#targetValue').value)});$('#targetDialog').close();toast('Meta atualizada');await load();if(detailGroupKey)renderDetail(detailGroupKey)}catch(err){toast(err.message)}});
$('#detailTargetBtn').addEventListener('click',async()=>{const g=groups().find(x=>x.key===detailGroupKey);if(!g)return;try{await requireAdmin();const t=targetOf(g);$('#targetGroupKey').value=g.key;$('#targetValue').value=t!=null?t.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}):'';$('#targetDialog').showModal()}catch(_){}});
$('#detailToggleBtn').addEventListener('click',async()=>{const g=groups().find(x=>x.key===detailGroupKey);if(!g)return;const active=g.offers.some(o=>o.active);try{await manage({action:'toggle_group',group_key:g.key,active:!active});toast(active?'Grupo pausado':'Grupo retomado');$('#detailDialog').close();await load()}catch(e){toast(e.message)}});
$('#detailDeleteBtn').addEventListener('click',async()=>{const g=groups().find(x=>x.key===detailGroupKey);if(!g||!confirm('Excluir este modelo, todas as lojas e todo o histórico?'))return;try{await manage({action:'delete_group',group_key:g.key});toast('Grupo excluído');$('#detailDialog').close();await load()}catch(e){toast(e.message)}});
$('#detailOffers').addEventListener('click',async e=>{const check=e.target.closest('[data-check-id]'),del=e.target.closest('[data-delete-offer]');try{if(check){check.disabled=true;check.textContent='…';const r=await manage({action:'check_now',id:check.dataset.checkId});toast(r.price?`Preço ${money(r.price)}`:'Verificado');await load();renderDetail(detailGroupKey)}if(del){if(!confirm('Remover somente esta loja do modelo?'))return;await manage({action:'delete',id:del.dataset.deleteOffer});toast('Oferta removida');await load();$('#detailDialog').close();const g=groups().find(x=>x.key===detailGroupKey);if(g)renderDetail(detailGroupKey)}}catch(err){toast(err.message)}finally{if(check){check.disabled=false;check.textContent='Verificar'}}});
load();setInterval(load,60000);