(()=>{
const URL='https://sziaumkwyxodhtuaxlhg.supabase.co/functions/v1/dashboard-data';
const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dt=v=>v?new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
let coupons=[];
function modelName(c,products){const p=products.find(x=>x.group_key===c.group_key);return p?.group_name||c.model||'Produto monitorado'}
function isFresh(c){return c.status==='active'&&c.validation_status==='cart_verified'&&c.cart_verified_at&&c.validation_expires_at&&new Date(c.validation_expires_at)>new Date()}
function render(products){const active=coupons.filter(isFresh).sort((a,b)=>new Date(b.cart_verified_at)-new Date(a.cart_verified_at));$('#couponBadge').textContent=active.length;const list=$('#couponList');if(!list)return;list.innerHTML='';$('#noCoupons').classList.toggle('hidden',active.length>0);for(const c of active){const card=document.createElement('article');card.className='coupon-card';card.innerHTML=`<div class="coupon-main"><div class="coupon-store">${esc(c.store)} <span class="trust-pill cart">✓ Carrinho confirmado</span></div><div class="coupon-name">${esc(c.title||'Cupom confirmado')}</div><div class="coupon-model"><span class="chip">${esc(c.model||'SKU monitorado')}</span><span class="coupon-empty-label">${esc(modelName(c,products))}</span></div></div><div class="coupon-code-wrap"><span>Código</span><div class="coupon-code"><code>${esc(c.code)}</code><button class="copy-coupon" type="button" data-copy-coupon="${esc(c.code)}">Copiar</button></div></div><div class="coupon-verified"><span>Confirmado no carrinho</span><strong>${dt(c.cart_verified_at)}</strong><small>${esc(c.validated_discount_text||c.discount_text||'Desconto aplicado com sucesso')}</small><small>Revalidar até ${dt(c.validation_expires_at)}</small></div><div class="coupon-actions"><a class="coupon-source" href="${esc(c.offer_url||c.source_url)}" target="_blank" rel="noopener">Abrir produto ↗</a></div>`;list.appendChild(card)}}
async function loadCoupons(){try{const r=await fetch(URL+'?coupon='+Date.now(),{cache:'no-store'});if(!r.ok)return;const d=await r.json();coupons=d.coupons||[];render(d.products||[])}catch(_){}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-copy-coupon]');if(!b)return;const code=b.dataset.copyCoupon;try{await navigator.clipboard.writeText(code);const old=b.textContent;b.textContent='Copiado!';setTimeout(()=>b.textContent=old,1500)}catch(_){prompt('Copie o cupom:',code)}});
loadCoupons();setInterval(loadCoupons,60000);
})();