(()=>{
const $=s=>document.querySelector(s);
const money=v=>v==null?'—':new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v));
const dayLabel=v=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v));
const shortDay=v=>new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit'}).format(new Date(v));
function groupData(){const map=new Map();for(const p of state.products||[]){const key=p.group_key||p.model||p.id;if(!map.has(key))map.set(key,{key,name:p.group_name||p.name,model:p.model||'',offers:[]});map.get(key).offers.push(p)}return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function dateKey(iso){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(iso))}
function buildDaily(group,offerId,days){const ids=new Set(offerId==='best'?group.offers.map(o=>o.id):[offerId]);const cutoff=Date.now()-Number(days)*86400000;const byDay=new Map();for(const h of state.history||[]){if(!ids.has(h.product_id))continue;const ts=new Date(h.checked_at).getTime();if(ts<cutoff)continue;const price=Number(h.price);if(!Number.isFinite(price))continue;const key=dateKey(h.checked_at);const product=group.offers.find(o=>o.id===h.product_id);const current=byDay.get(key);if(!current||price<current.price)byDay.set(key,{date:key,iso:h.checked_at,price,store:product?.store||'Loja',product_id:h.product_id,readings:(current?.readings||0)+1});else current.readings=(current.readings||0)+1}
return [...byDay.values()].sort((a,b)=>a.date.localeCompare(b.date))}
function populate(){const gs=groupData(),sel=$('#historyModel');if(!sel)return;const previous=sel.value;sel.innerHTML=gs.map(g=>`<option value="${g.key}">${g.name}</option>`).join('');if(gs.some(g=>g.key===previous))sel.value=previous;else if(gs.length)sel.value=gs[0].key;populateStores();renderHistory()}
function populateStores(){const g=groupData().find(x=>x.key===$('#historyModel').value),sel=$('#historyStore');if(!g||!sel)return;const previous=sel.value;sel.innerHTML='<option value="best">Menor preço entre todas as lojas</option>'+g.offers.map(o=>`<option value="${o.id}">${o.store||new URL(o.url).hostname}</option>`).join('');if([...sel.options].some(o=>o.value===previous))sel.value=previous}
function renderHistory(){const container=$('#historyChart');if(!container)return;const g=groupData().find(x=>x.key===$('#historyModel').value);if(!g){container.innerHTML='';return}const data=buildDaily(g,$('#historyStore').value,$('#historyRange').value);const empty=$('#historyEmpty'),panel=$('#historyPanel');empty.classList.toggle('hidden',data.length>0);panel.classList.toggle('hidden',data.length===0);if(!data.length)return;const vals=data.map(x=>x.price),min=Math.min(...vals),max=Math.max(...vals),first=vals[0],last=vals.at(-1),delta=last-first;$('#historyMin').textContent=money(min);$('#historyMax').textContent=money(max);$('#historyFirst').textContent=money(first);$('#historyChange').textContent=(delta>0?'+':'')+money(delta);$('#historyChange').style.color=delta<0?'var(--green-dark)':delta>0?'var(--red)':'var(--text)';
const W=980,H=320,L=76,R=24,T=22,B=52,range=Math.max(max-min,1),pad=range*.12,yMin=Math.max(0,min-pad),yMax=max+pad,x=i=>data.length===1?(L+W-R)/2:L+i*(W-L-R)/(data.length-1),y=v=>T+(yMax-v)*(H-T-B)/(yMax-yMin);let grid='',labels='';for(let i=0;i<5;i++){const yy=T+i*(H-T-B)/4,val=yMax-i*(yMax-yMin)/4;grid+=`<line class="history-grid-line" x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}"/>`;labels+=`<text class="history-axis" x="${L-10}" y="${yy+4}" text-anchor="end">${Math.round(val).toLocaleString('pt-BR')}</text>`}const pts=data.map((d,i)=>[x(i),y(d.price)]),path=pts.map((p,i)=>(i?'L':'M')+p[0]+' '+p[1]).join(' '),area=`M${pts[0][0]} ${H-B} `+pts.map(p=>`L${p[0]} ${p[1]}`).join(' ')+` L${pts.at(-1)[0]} ${H-B} Z`;const every=Math.max(1,Math.ceil(data.length/7));let xlabels='';data.forEach((d,i)=>{if(i%every===0||i===data.length-1)xlabels+=`<text class="history-axis" x="${x(i)}" y="${H-18}" text-anchor="middle">${shortDay(d.iso)}</text>`});container.innerHTML=`<div class="history-canvas"><svg class="history-chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Histórico diário de preço de ${g.name}">${grid}${labels}${xlabels}<path class="history-area" d="${area}"/><path class="history-line" d="${path}"/>${data.map((d,i)=>`<circle class="history-point" cx="${x(i)}" cy="${y(d.price)}" r="5" data-history-point="${i}" tabindex="0"><title>${dayLabel(d.iso)}: ${money(d.price)} · ${d.store}</title></circle>`).join('')}</svg><div id="historyTooltip" class="history-tooltip hidden"></div></div>`;const tip=$('#historyTooltip');container.querySelectorAll('[data-history-point]').forEach(el=>{const show=()=>{const d=data[Number(el.dataset.historyPoint)],svg=container.querySelector('svg'),rect=svg.getBoundingClientRect(),cx=Number(el.getAttribute('cx'))/W*rect.width,cy=Number(el.getAttribute('cy'))/H*rect.height;tip.innerHTML=`<strong>${dayLabel(d.iso)}</strong><br>${money(d.price)} · ${d.store}`;tip.style.left=cx+'px';tip.style.top=cy+'px';tip.classList.remove('hidden')};el.addEventListener('mouseenter',show);el.addEventListener('focus',show);el.addEventListener('mouseleave',()=>tip.classList.add('hidden'));el.addEventListener('blur',()=>tip.classList.add('hidden'))});$('#historyTableBody').innerHTML=data.slice().reverse().map(d=>`<tr><td>${dayLabel(d.iso)}</td><td><strong>${money(d.price)}</strong></td><td>${d.store}</td><td>${d.readings||1}</td></tr>`).join('')}
document.addEventListener('DOMContentLoaded',()=>{const m=$('#historyModel'),s=$('#historyStore'),r=$('#historyRange');m?.addEventListener('change',()=>{populateStores();renderHistory()});s?.addEventListener('change',renderHistory);r?.addEventListener('change',renderHistory);document.querySelector('[data-tab="history"]')?.addEventListener('click',renderHistory);setTimeout(populate,700);setInterval(()=>{if(document.querySelector('[data-tab="history"]')?.classList.contains('active'))populate()},60000)});
})();